export const ADMIN_CHECK_START = "ADMIN_CHECK_START";
export const ADMIN_CHECK_COMPLETE = "ADMIN_CHECK_COMPLETE";
export const ADMIN_CHECK_ERROR = "ADMIN_CHECK_ERROR";

export const ADMIN_FETCH_START = "ADMIN_FETCH_START";
export const ADMIN_FETCH_COMPLETE = "ADMIN_FETCH_COMPLETE";
export const ADMIN_FETCH_ERROR = "ADMIN_FETCH_ERROR";

export const ADMIN_UPDATE_START = "ADMIN_UPDATE_START";
export const ADMIN_UPDATE_COMPLETE = "ADMIN_UPDATE_COMPLETE";
export const ADMIN_UPDATE_ERROR = "ADMIN_UPDATE_ERROR";
