export const USER_AUTH_START = "USER_AUTH_START";
export const USER_OTP_COMPLETE = "USER_OTP_COMPLETE";
export const USER_AUTH_COMPLETE = "USER_AUTH_COMPLETE";
export const USER_AUTH_FAILURE = "USER_AUTH_FAILURE";
