export const LOAN_FETCH_START = "LOAN_FETCH_START";
export const LOAN_FETCH_COMPLETE = "LOAN_FETCH_COMPLETE";
export const LOAN_FETCH_ERROR = "LOAN_FETCH_ERROR";

export const LOAN_POST_START = "LOAN_POST_START";
export const LOAN_POST_COMPLETE = "LOAN_POST_COMPLETE";
export const LOAN_POST_ERROR = "LOAN_POST_ERROR";
